name: Compress and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compress code into .tar.gz
        run: |
          tar --exclude='*.git*' --exclude='*.github*' -czf crescent.tar.gz *

      - name: Upload release asset
        uses: actions/upload-artifact@v2
        with:
          name: release-code
          path: release-code.tar.gz
